# -*- coding: utf-8 -*-
"""Covid_19 test project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gvRjGTyTeGIfVLUi4bJzV9D4YY7xWD0l
"""

import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/niteen11/data301_predictive_analytics_machine_learning/66deff40ebee4baa81e91dad09c8caa8e5eada54/data/COVID-19_Daily_Testing.csv')

df

df.head

df.shape

df.columns

x = df[[ 'Day', 'Date', 'Tests', 'Cases',]]

x

y = df[df['Day'] == 'Monday']

z = y[['Day', 'Date', 'Cases', 'Tests']]

z
## compairing cases and tests done on Monday

z.sum

a = df[['Date', 'Day', 'Tests', 'Cases']]

b = a['Cases']

b.head(10)

c = a.sort_values(by = 'Cases', ascending= False)

c
## Which day had the most amount to testing

d = a.sort_values(by= 'Tests', ascending= False)

d
## Which day had the most testing

